### ISSUE TITLE
allow config file write failure

### ISSUE THREAD

**Issue by tkellen** [gulpjs/v8flags#29]
from https://github.com/js-cli/js-v8flags/issues/22#issuecomment-112119183

> What do you think about just throwing an annoying warning in gulp if this file can't be cached, and allowing it to just run anyway? For CI servers (where this seems to be the most error prone) the performance hit of having to invoke node to get the v8 flag listing should be meaningless.

**Comment by phated** [comment]
++ really hoping someone from the community can contribute this back to us before gulp-cli hits 1.0

**Comment by phated** [comment]
Now that #31 is merged, is this solved?

**Comment by phated** [comment]
I'm pretty sure this is solved.
