### ISSUE TITLE
Deprecate node 0.X support

### ISSUE THREAD

**Issue by Siilwyn** [gulpjs/v8flags#40]
In the future it would be good to stop testing against these old versions (in the CI). This allows the removal of the `user-home` dependency which is stuck in version 1.1.1 and replace it with the native `os.homedir` function. But mainly because it saves some developer time not having to test against these old versions.

0.X versions are long gone:
![image](https://user-images.githubusercontent.com/5701149/28947073-4f28a1ae-78ae-11e7-8a16-f65642b07314.png)

**Comment by phated** [comment]
This would be far-future (like 2018+) but I don't think it's necessary for 1 platform feature.  I'll also be switching out the library for a different one so it isn't "stuck".

**Comment by jonschlinkert** [comment]
fwiw I think one of our projects had issues with `user-home` (cc @doowb).  might be worth considering [homedir-polyfill](https://www.npmjs.com/package/homedir-polyfill)

**Comment by doowb** [comment]
Yeah, `homedir-polyfill` was designed specifically for supporting older versions of node that don't have `os.homedir`. I went through the implementation in `libuv` to ensure the logic was as close to the same as possible and uses `os.homedir` if it's available. We've been using it for a while now and I don't recall any issues.

**Comment by phated** [comment]
As of node 10.10, the [`allowedNodeEnvironmentFlags`](https://nodejs.org/api/process.html#process_process_allowednodeenvironmentflags) global is available so there will be no need for this module in the future.  This will continue to live on for older node versions but I'm going to close this.
