### ISSUE TITLE
Store .v8flags.*.json files in subfolder

### ISSUE THREAD

**Issue by selfagency** [gulpjs/v8flags#52]
It would be lovely if the module would create a subfolder `.v8flags` to store the cached `.v8flags.*.json` files it outputs instead of the home folder so as not to create unnecessary clutter. I use various Node versions for different projects and have a dozen `.v8flags.*.json` files in my home folder.

**Comment by Siilwyn** [comment]
This was done in version 3.0.0 make sure you're using an updated `v8flags`.

**Comment by Siilwyn** [comment]
Also note this module is not relevant anymore with newer Node versions: https://github.com/gulpjs/v8flags/issues/51

**Comment by selfagency** [comment]
Thanks.
