### ISSUE TITLE
Consider using SHA-256 over MD5 for the config file

### ISSUE THREAD

**Issue by silverwind** [gulpjs/v8flags#56]
https://github.com/gulpjs/v8flags/blob/master/index.js#L19 contains a MD5 usage. When Node.js is built with FIPS compliance, that line triggers below error because MD5 is disabled in those builds:

````
Error: error:060800A3:digital envelope routines:EVP_DigestInit_ex:disabled for fips
    at new Hash (internal/crypto/hash.js:48:19)
    at Object.createHash (crypto.js:109:10)
    at Object.<anonymous> (node_modules/v8flags/index.js:19:89)
````

Consider using something more collision-resistant like SHA-256 instead.

**Comment by contra** [comment]
This seems like a reasonable request - want to send a PR @silverwind ?

**Comment by silverwind** [comment]
https://github.com/gulpjs/v8flags/pull/57

**Comment by tgflet** [comment]
Bump, I could really use this fix in a project. It is breaking the project when enforcing FIPS when enforcing FIPS because MD5 is not FIPS compliant @silverwind @phated
